### PR TITLE
Adds a snake emoji as a favicon

### PR DESCRIPTION
**Pull request by gingerchew**
Adds a snake emoji as a favicon using the method here https://css-tricks.com/emoji-as-a-favicon/ 

Using a `data:image/svg+xml,` data-uri and the svg `<text>` element, you can put an emoji as the favicon easily.

### CODE REVIEW

**Comment by mccutchen** [comment]
Ooh I like this idea!  Would you mind running `make` (or `make build`) to update the generated `index.html` file and commit the results?

**Comment by mccutchen** [comment]
> Ooh I like this idea! Would you mind running `make` (or `make build`) to update the generated `index.html` file and commit the results?

(If you're running Windows or some other OS where `make` and `python` aren't readily available, just let me know and I'll take care of this later tonight!)

**Comment by gingerchew** [comment]
Yeah, i think something isn't set up right on my end, so i appreciate it :)

**Comment by mccutchen** [comment]
> i think something isn't set up right on my end

Heh, it seems like the Makefile is kinda broken, so I don't think this is just on your end.  Anyway, I rebuilt, pushed an updated commit up.  LGTM locally.

Thanks for the contribution!

**Pull request merged**
