### PR TITLE
add live demo of strftime

### PR DESCRIPTION
**Pull request by swalladge**
This adds a text input to enter a format string which is processed by strftime.js and output below while the user types. Handy for quickly testing what a format string will look like once processed.

### CODE REVIEW

**Comment by swalladge** [comment]
To anyone coming across this PR and wants to see how this looks, I have a live version at https://swalladge.github.io/strftime/

**Comment by icemac** [comment]
Cool feature!

**Comment by javierdaza** [comment]
Works great!

**Comment by Strangemother** [comment]
This is great - It's a sincere shame it's been in PR for so long. Are these conflicts the issue?

**Comment by swalladge** [comment]
@Strangemother ah these conflicts were new; thanks for the heads up. I've resolved them now. 

@mccutchen ah you interested in looking at this PR? :)

**Comment by swalladge** [comment]
Closing because upstream has some major updates and I don't have time to fix conflicts.

**Pull request closed without merging**
