### PR TITLE
Change hour to 7

### PR DESCRIPTION
**Pull request by cxong**
This distinguishes hour values from month, making things easier to find

### CODE REVIEW

**Comment by mccutchen** [comment]
@cxong this is a good idea — I think it would also be nice to change the day to something > 12 to disambiguate day and month, too.  Would you mind adding that change?

**Comment by cxong** [comment]
bump

**Comment by mccutchen** [comment]
@cxong sorry, I didn't know you had pushed another commit — I only get notifications for comments.  Thanks for the contribution!

**Comment by mccutchen** [comment]
Deployed! http://strftime.org/

**Comment by DirtyJerz** [comment]
an hour > 12 would also help differentiate between 12/24 hr clocks.

**Pull request merged**
